# Generated by Django 4.1.3 on 2022-11-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jposting', models.DateTimeField()),
                ('jlocation', models.TextField()),
                ('joffersal', models.IntegerField()),
                ('jquali', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
